# Generated by Django 5.2.8 on 2025-11-22 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('annotated_image', models.ImageField(upload_to='annotated/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.IntegerField()),
                ('bbox_y1', models.IntegerField()),
                ('bbox_x2', models.IntegerField()),
                ('bbox_y2', models.IntegerField()),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='vision.detectionresult')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
